Shared: Fix specific node for remote PoW
iotaledger/trinity-wallet pull request #2130
Opened 2019-08-12 17:02 UTC by cvarley100

## Description

- Fixes various issues with setting a specific node for remote PoW
- Removes old PoW setting
- Fixes mobile UI for node settings

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on iOS

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

2019-08-12 23:52 UTC, rajivshah3 requested changes

2019-08-12 23:52 UTC, rajivshah3 commented on src/desktop/src/ui/views/settings/Node.js
> +        if (powNode.length ^ this.props.powNode.length) {
```suggestion
        if (powNode.length ^ settings.powNode.length) {
```

>124:30  error  Stateless functional components should not use this  react/no-this-in-sfc

https://buildkite.com/iota-foundation/trinity-desktop-prs/builds/4935#8a8cb4cb-3e4f-495a-93f3-f5a1f8ff734f/54-259

2019-08-12 23:52 UTC, rajivshah3 commented on src/desktop/src/ui/views/settings/Node.js
> +            this.props.changePowSettings();
```suggestion
            actions.changePowSettings();
```

>125:13  error  Stateless functional components should not use this  react/no-this-in-sfc

https://buildkite.com/iota-foundation/trinity-desktop-prs/builds/4935#8a8cb4cb-3e4f-495a-93f3-f5a1f8ff734f/54-260

2019-08-12 23:52 UTC, rajivshah3 commented on src/mobile/src/ui/views/wallet/NodeSettings.js
> +         const powNode = this.state.powNode.length === 0 && availablePowNodes.length ? availablePowNodes[0].url : '';
>276:26  error  Use callback in setState when referencing the previous state  react/no-access-state-in-setstate

https://buildkite.com/iota-foundation/trinity-mobile-prs/builds/4986#647b529d-0083-4b4e-9dfa-f981c8d7f627/54-297

2019-08-13 23:05 UTC, rajivshah3 commented on src/shared/libs/iota/NodesManager.js
> +                // If auto primaru node switching is disabled, just connect to the selected (primary) node
```suggestion
                // If auto primary node switching is disabled, just connect to the selected (primary) node
```

2019-08-13 23:05 UTC, rajivshah3 commented on src/shared/locales/en/translation.json
> +        "autoNodeList": "Use official node list",
Would `default` sound better here?

2019-08-14 12:54 UTC, rihardsgravis approved these changes

2019-08-14 13:08 UTC, merged