WIP: fix: MoonPay enhancements/fixes
iotaledger/trinity-wallet pull request #2451
Opened 2020-01-06 05:26 UTC by rajivshah3

# Description

Fixes and enhancements to MoonPay registration and purchase process:
- Use placeholder for DOB field
- Validate DOBs
- Convert commas to periods when used as decimal separators

Fixes #2400 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

- Tested on iOS simulator

# Checklist:

- [ ] My code follows the style guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

2020-01-06 05:29 UTC, rajivshah3 commented on src/mobile/src/ui/views/wallet/exchanges/MoonPay/UserBasicInfo.js
> +            return this.props.generateAlert('error', 'Invalid DOB', 'Invalid DOB');
To do: Add translation string

2020-01-06 05:29 UTC, rajivshah3 commented on src/mobile/src/ui/views/wallet/exchanges/MoonPay/AddAmount.js
>                              </View>
To do: Fee will still sometimes show as `0` when using commas

2020-01-06 05:29 UTC, rajivshah3 commented on src/mobile/src/ui/views/wallet/exchanges/MoonPay/AddAmount.js
>          } = this.props;
To do: Amount should be validated with something like `Number(this.parseAmount(amount)) !== NaN`

2020-01-13 16:44 UTC, cvarley100 commented
Is there a reason this is mobile only?

2020-01-13 17:14 UTC, rajivshah3 commented
I happened to start on mobile and was planning to do desktop afterwards

2020-01-17 10:21 UTC, laumair requested changes

2020-01-17 10:21 UTC, laumair commented on src/desktop/src/ui/views/exchanges/MoonPay/ReviewPurchase.js
> +                        : createTransaction
Why aren't we calling `createTransaction` here? If purchases aren't suspended, form submission won't do anything.

2020-01-20 14:13 UTC, laumair approved these changes
Looks good to me! Nice work.

2020-01-20 14:44 UTC, merged