fix(shared): autopromotion improvements
iotaledger/trinity-wallet pull request #3029
Opened 2020-09-03 20:46 UTC by cvarley100

# Description of change

Various autopromotion fixed:
- Turns off quorum
- Ensures all nodes are used for finding a promotable tail (as oppose to just 
- Correctly handles `unknown tail transaction` errors on `getTipInfo`
- Prioritises promotion of value transfers

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Tested on Mac OS debug

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

2020-09-04 19:24 UTC, rajivshah3 requested changes

2020-09-04 19:24 UTC, rajivshah3 commented on src/desktop/src/ui/global/Polling.js
> +            let bundleHashToPromote = !isEmpty(valueBundleHashes)
```suggestion
            const bundleHashToPromote = !isEmpty(valueBundleHashes)
```

2020-09-04 19:24 UTC, rajivshah3 commented on src/mobile/src/ui/components/Poll.js
> +            let bundleHashToPromote = !isEmpty(valueBundleHashes)
```suggestion
            const bundleHashToPromote = !isEmpty(valueBundleHashes)
```

2020-09-04 19:24 UTC, rajivshah3 commented on src/shared/libs/iota/extendedApi.js
> +        return response.json().then((res) => {
Shouldn't we check the response code before parsing the JSON?

2020-09-07 10:46 UTC, laumair approved these changes

2020-09-07 11:25 UTC, merged