Update to React Native 0.56
iotaledger/trinity-wallet pull request #342
Opened 2018-09-07 14:13 UTC by cvarley100

# Description

_Please include a summary of the change. Include the motivation for the change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

- Test A
- Test B

# Checklist:

_Please delete items that are not relevant._

- [ ] My code follows the style guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] For changes to `mobile` that include native code (including React Native modules): I have verified that both iOS and Android successfully build in both `Debug` and `Release` modes
- [ ] For changes to `shared`: If applicable, I have verified that my changes are implemented correctly in `desktop` and `mobile`

2018-09-07 15:27 UTC, rajivshah3 requested changes
Just some minor changes because the upgrade tool probably took some stuff out. Also, the `trinity-mobile` and `trinity-mobile-tvOS` folders should be deleted because RN is automatically creating them. 

The CI is failing because of https://github.com/facebook/react-native/issues/19859, this might be fixed by updating Jest to `^23.2.0`

2018-09-07 15:27 UTC, rajivshah3 commented on src/mobile/android/app/BUCK
> +    package = "com.trinity-mobile",
Was this an automated change? We should leave it alone to avoid breaking something

2018-09-07 15:27 UTC, rajivshah3 commented on src/mobile/android/app/BUCK
> +    package = "com.trinity-mobile",
See above

2018-09-07 15:27 UTC, rajivshah3 commented on src/mobile/android/gradle.properties
> -org.gradle.jvmargs=-Xmx1536m
This is necessary in order to allocate enough memory for the build process. The deployment on CI may fail if this is removed

2018-09-07 15:27 UTC, rajivshah3 commented on src/mobile/ios/iotaWallet/iotaWallet.entitlements
> -		<string>CloudDocuments</string>
This may need to be kept in for the document picker

2018-09-11 18:16 UTC, closed without merging

2018-09-11 18:20 UTC, cvarley100 commented
Closed. Updating to 0.55.4 instead due to breaking changes in 0.56.

See https://github.com/iotaledger/trinity-wallet/pull/358 and https://github.com/iotaledger/trinity-wallet/pull/359